[package]
name = "cidrscan"
version = "0.1.0"
authors = ["TheRealMkadmi <wahibmkadmi16@gmail.com>"]
edition = "2021"
description = "A high-performance memory-resident Patricia tree with TTL support for CIDR tagging and IP lookups."
license = "MIT"
repository = "https://github.com/TheRealMkadmi/cidrscan-rs"

[dependencies]
raw_sync = "0.1.5"
shared_memory = "0.12"
parking_lot = "0.12"     # fast, fair Mutex for free-list
once_cell   = "1.21"     # per-process handle cache

[dev-dependencies]
proptest = "1"
num_cpus = "1"
rand = "0.9.1"
[features]
trace = []
