[package]
name = "cidrscan"
version = "0.1.0"
authors = ["TheRealMkadmi <wahibmkadmi16@gmail.com>"]
edition = "2021"
description = "A high-performance memory-resident Patricia tree with TTL support for CIDR tagging and IP lookups."
license = "MIT"
repository = "https://github.com/TheRealMkadmi/cidrscan-rs"

[dependencies]
shared_memory = "0.12.4"      # Cross‑platform shared memory support 
raw_sync      = "0.1.5"       # Provides Mutex, RwLock for shared memory
spin          = "0.10.0"       # Spin-based locks for synchronization
libc = "0.2.172"
once_cell = "1.21.3"
lock_api = "0.4.12"
cfg-if = "1.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32", "Win32_Foundation", "Win32_Security", "Win32_System_Threading"] }




[lib]
name = "cidrscan"
crate-type = ["rlib", "cdylib"]

[build-dependencies]
cbindgen = "0.24"
