#ifndef CIDRSCAN_H
#define CIDRSCAN_H

/* Warning: This file is autogenerated by cbindgen. Do not modify directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct PatriciaTree PatriciaTree;

/**
 * Create or open a shared‑memory tree (C API)
 */
int32_t patricia_open(const uint8_t *name, uintptr_t name_len, uintptr_t capacity);

/**
 * Insert a key with TTL (C API)
 */
void patricia_insert(struct PatriciaTree *tree,
                     uint64_t key_high,
                     uint64_t key_low,
                     uint8_t prefix_len,
                     uint64_t ttl);

/**
 * Lookup a key (C API)
 */
bool patricia_lookup(struct PatriciaTree *tree, uint64_t key_high, uint64_t key_low);

/**
 * Delete a key (C API)
 */
void patricia_delete(struct PatriciaTree *tree, uint64_t key_high, uint64_t key_low);

#endif /* CIDRSCAN_H */
