rustflags = ["-C", "link-arg=-Wl,-undefined,dynamic_lookup"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar     = "aarch64-linux-gnu-ar" 

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.i686-pc-windows-msvc]
linker = "rust-lld"
