[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar     = "aarch64-linux-gnu-ar" 

[target.'cfg(not(target_os = "windows"))'] 
rustflags = ["-C", "link-arg=-Wl,-undefined,dynamic_lookup"]

[target.'cfg(target_os = "windows")'] 
linker = "rust-lld"

