# .github/workflows/build-and-release.yml
name: Build and Release Libraries

on:
  push:
    tags: ['v*']
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always

###############################################################################
# 1. Test suite
###############################################################################
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --workspace

###############################################################################
# 2. Native C-ABI libraries (Linux, Windows, macOS)
###############################################################################
  build-libs:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      # cross binary cached – Linux only
      - if: runner.os == 'Linux'
        uses: actions/cache@v4
        id: cache-cross
        with:
          path: ~/.cargo/bin/cross
          key: cross-bin
      - if: runner.os == 'Linux' && steps.cache-cross.outputs.cache-hit != 'true'
        run: cargo install cross --git https://github.com/cross-rs/cross --locked

      - uses: Swatinem/rust-cache@v2

      # Install Info-ZIP so that the bash loop can call `zip`
      - name: Install zip CLI (Windows)
        if: runner.os == 'Windows'
        run: choco install -y zip

      - name: Add required Rust targets
        run: |
          rustup target add x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu x86_64-pc-windows-msvc x86_64-apple-darwin aarch64-apple-darwin

      - name: Build & package targets for this OS
        shell: bash
        run: |
          set -euo pipefail
          case "$RUNNER_OS" in
            Linux)
              TARGETS=("x86_64-unknown-linux-gnu" "aarch64-unknown-linux-gnu")
              ;;
            Windows)
              TARGETS=("x86_64-pc-windows-msvc")
              ;;
            macOS)
              TARGETS=("x86_64-apple-darwin" "aarch64-apple-darwin")
              ;;
          esac
          mkdir -p packages
          for TARGET in "${TARGETS[@]}"; do
            case "$TARGET" in
              x86_64-unknown-linux-gnu)  NAME=linux-x86_64 ;;
              aarch64-unknown-linux-gnu) NAME=linux-aarch64 ;;
              x86_64-pc-windows-msvc)    NAME=windows-x86_64 ;;
              x86_64-apple-darwin|aarch64-apple-darwin) NAME=macos-${TARGET%%-*} ;;
            esac

            # build ─────────────
            if [ "$RUNNER_OS" = "Linux" ]; then
              cross build --release --manifest-path cidrscan_core/Cargo.toml --target "$TARGET"
            else
              cargo build --release --manifest-path cidrscan_core/Cargo.toml --target "$TARGET"
            fi

            SRC=target/$TARGET/release
            INC=cidrscan_core/include

            mkdir -p "packages/$NAME"
            cp "$INC/cidrscan.h" "packages/$NAME/"
            # Copy shared + static libraries
            for PAT in "libcidrscan*.so" "libcidrscan*.a" "cidrscan*.dll" "cidrscan*.lib" "libcidrscan*.dylib"; do
              cp "$SRC/$PAT" "packages/$NAME/" 2>/dev/null || true
            done

            (cd "packages/$NAME" && zip -rq "../../$NAME.zip" .)
            echo "::group::Contents of $NAME.zip"
            unzip -l "$NAME.zip"
            echo "::endgroup::"
          done

          # macOS only – fuse into one universal dylib
          if [ "$RUNNER_OS" = "macOS" ]; then
            mkdir -p packages/macos-universal
            lipo -create \
              target/x86_64-apple-darwin/release/libcidrscan_core.dylib \
              target/aarch64-apple-darwin/release/libcidrscan_core.dylib \
              -output packages/macos-universal/libcidrscan_core.dylib
            cp cidrscan_core/include/cidrscan.h packages/macos-universal/
            (cd packages/macos-universal && zip -rq "../../macos-universal.zip" .)
            echo "::group::Contents of macos-universal.zip"
            unzip -l macos-universal.zip
            echo "::endgroup::"
          fi

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            linux-*.zip
            windows-*.zip
            macos-*.zip
            macos-universal.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

###############################################################################
# 3. PHP extensions (+ stubs) for PHP 8.3 & 8.4 across OS/arch/TS combos
###############################################################################
  build-php:
    needs: test
    strategy:
      matrix:
        include:
          # Linux NTS (x86_64 + aarch64)
          - { os: ubuntu-latest, osname: linux, arch: x86_64, target: x86_64-unknown-linux-gnu, libext: so, phpts: nts, version: '8.3' }
          - { os: ubuntu-latest, osname: linux, arch: aarch64, target: aarch64-unknown-linux-gnu, libext: so, phpts: nts, version: '8.3' }
          - { os: ubuntu-latest, osname: linux, arch: x86_64, target: x86_64-unknown-linux-gnu, libext: so, phpts: nts, version: '8.4' }
          - { os: ubuntu-latest, osname: linux, arch: aarch64, target: aarch64-unknown-linux-gnu, libext: so, phpts: nts, version: '8.4' }

          # macOS NTS (x86_64 + aarch64)
          - { os: macos-latest, osname: macos, arch: x86_64, target: x86_64-apple-darwin, libext: so, phpts: nts, version: '8.3' }
          - { os: macos-latest, osname: macos, arch: aarch64, target: aarch64-apple-darwin, libext: so, phpts: nts, version: '8.3' }
          - { os: macos-latest, osname: macos, arch: x86_64, target: x86_64-apple-darwin, libext: so, phpts: nts, version: '8.4' }
          - { os: macos-latest, osname: macos, arch: aarch64, target: aarch64-apple-darwin, libext: so, phpts: nts, version: '8.4' }

          # Windows NTS & TS (x86_64 only)
          - { os: windows-latest, osname: windows, arch: x86_64, target: x86_64-pc-windows-msvc, libext: dll, phpts: nts, version: '8.3' }
          - { os: windows-latest, osname: windows, arch: x86_64, target: x86_64-pc-windows-msvc, libext: dll, phpts: ts,  version: '8.3' }
          - { os: windows-latest, osname: windows, arch: x86_64, target: x86_64-pc-windows-msvc, libext: dll, phpts: nts, version: '8.4' }
          - { os: windows-latest, osname: windows, arch: x86_64, target: x86_64-pc-windows-msvc, libext: dll, phpts: ts,  version: '8.4' }
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install aarch64 cross-compiler
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install macOS cross-compilers
        if: runner.os == 'macOS'
        run: brew install llvm

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
        env:
          phpts: ${{ matrix.phpts }}

      - if: runner.os == 'Windows'
        id: php_sdk
        uses: php/setup-php-sdk@v0.10
        with:
          version: ${{ matrix.version }}
          arch: x64
          ts: ${{ matrix.phpts }}

      - if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: ${{ steps.php_sdk.outputs.toolset }}

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}-${{ matrix.target || '' }}

      - run: cargo install cargo-php --locked

      - name: Build extension & generate stubs
        shell: bash
        run: |
          set -euo pipefail
          OUTDIR="packages/php-${{ matrix.version }}_${{ matrix.osname }}_${{ matrix.arch }}_${{ matrix.phpts }}"
          mkdir -p "$OUTDIR"

          # Inline build.sh logic
          cargo build --manifest-path cidrscan_php/Cargo.toml --release --target="${{ matrix.target }}"

          SRC="target/${{ matrix.target }}/release"
          # macOS builds yield .dylib; Linux/Windows produce .so/.dll
          ART="$(ls "$SRC"/libcidrscan_php.{dylib,${{ matrix.libext }}} 2>/dev/null | head -n1)"
          if [ -z "$ART" ]; then
            echo "::error file=$SRC::cidrscan_php.{${{ matrix.libext }},dylib} not found"; exit 1
          fi
          # Always store as .so so PHP can load it uniformly
          cp "$ART" "$OUTDIR/cidrscan_php.${{ matrix.libext }}"
          cargo php stubs --manifest cidrscan_php/Cargo.toml -o "$OUTDIR/cidrscan_php.phpstub"

      - name: Zip PHP deliverable
        shell: bash
        run: |
          ZIP="cidrscan_php_${{ matrix.version }}_${{ matrix.osname }}_${{ matrix.arch }}_${{ matrix.phpts }}.zip"
          (cd packages && zip -rq "../$ZIP" "php-${{ matrix.version }}_${{ matrix.osname }}_${{ matrix.arch }}_${{ matrix.phpts }}")
          echo "::group::Contents of $ZIP"
          unzip -l "$ZIP"
          echo "::endgroup::"

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: cidrscan_php_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

###############################################################################
# 5. Merge macOS PHP extensions into universal .so (for each PHP version)
###############################################################################
  merge-php-macos-universal:
    needs: build-php
    runs-on: macos-latest
    strategy:
      matrix:
        version: [ '8.3', '8.4' ]
    steps:
      - uses: actions/checkout@v4
      - name: Download PHP extension artifacts
        uses: actions/download-artifact@v4
        with:
          name: |
            cidrscan_php_${{ matrix.version }}_macos_x86_64_nts.zip
            cidrscan_php_${{ matrix.version }}_macos_aarch64_nts.zip

      - name: Unzip artifacts
        run: |
          unzip cidrscan_php_${{ matrix.version }}_macos_x86_64_nts.zip -d x86_64
          unzip cidrscan_php_${{ matrix.version }}_macos_aarch64_nts.zip -d aarch64

      - name: Merge PHP extensions into universal binary
        run: |
          mkdir -p universal
          lipo -create \
            x86_64/cidrscan_php.so \
            aarch64/cidrscan_php.so \
            -output universal/cidrscan_php.so

      - name: Zip universal PHP extension
        run: |
          cd universal
          zip ../cidrscan_php_${{ matrix.version }}_macos_universal_nts.zip cidrscan_php.so

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: cidrscan_php_${{ matrix.version }}_macos_universal_nts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
